BEGIN;

-- 1. Insertar a Castor Pérez en DCLIENTE
INSERT INTO DCLIENTE (
    CODCLIENTE, NOMCLIENTE, CODSBS, PKCLASEPERSONA, CODCLASEPERSONA, DESCLASEPERSONA, 
    FECHAINGRESOCAJA, EMAIL, PKACTIVIDADECONOMICA, PKTIPODOCUMENTOIDENTIDAD, 
    CODTIPODOCUMENTOIDENTIDAD, DESTIPODOCUMENTOIDENTIDAD, NUMERODOCUMENTOIDENTIDAD, 
    MONTODEINGRESO, FECHANACIMIENTO, SEXO, ESTADOCIVIL, PKUBIGEO, TELEFONO, 
    TIPOFUENTEINGRESO, MONTOINGRESONETO, PKPAIS
) VALUES (
    'CLI002010', 'Pérez, Castor', 'SBS002010', 
    (SELECT PKCLASEPERSONA FROM DCLASEPERSONA WHERE CODCLASEPERSONA='03'), '03', 'Persona Natural con Negocio',
    '2026-02-02', 'castor.perez@email.com', 
    (SELECT PKACTIVIDADECONOMICA FROM DACTIVIDADECONOMICA WHERE CODACTIVIDADECONOMICA='4711'),
    (SELECT PKTIPODOCUMENTOIDENTIDAD FROM DTIPODOCUMENTOIDENTIDAD WHERE CODTIPODOCUMENTOIDENTIDAD='01'), '01', 'DNI', 
    '11202010', 3000.00, '1985-05-15', 'M', 'C',
    (SELECT PKUBIGEO FROM DUBIGEO WHERE CODDISTRITO='120101'), '964123456', 
    'NE', 2500.00, (SELECT PKPAIS FROM DPAIS WHERE CODPAIS='PER')
);

-- 2. Crear la cuenta de ahorros en DCUENTAAHORRO
INSERT INTO DCUENTAAHORRO (CODCUENTAAHORRO, PKCLIENTE, FECULTACTUALIZACION) VALUES
('AHO0000801', (SELECT PKCLIENTE FROM DCLIENTE WHERE CODCLIENTE='CLI002010'), NOW());

-- 3. Crear el saldo en FCUENTAAHORRO (con saldo inicial de S/ 500.00)
INSERT INTO FCUENTAAHORRO (
    PERIODODIA, PKCUENTAAHORRO, PKPRODUCTOAHORRO, PKMONEDA, PKTIPOCUENTAAHORRO, PKTIPOTASAAHORRO, 
    PKCLIENTE, PKAUXILIAR, PKOPERADOR, PKAGENCIA, PKESTADOCUENTA, TIPOCAMBIO, 
    MONTOSALDOCAPITALTOTAL, MONTOSALDOINTERESTOTAL, MONTOSALDOPROMEDIOTOTAL, FECHAAPERTURACUENTA, 
    MONTODEPOSITOAPERTURA, TASAINTERESCUENTA, TASAEFECTIVAANUAL, NROTITULARES, NROFIRMAS, 
    FLAGEXONERACIONIMPUESTO, FLAGEXONERACIONCOMISION, FLAGCUENTAPROMOCION, NROOPERACIONESLIBRES, 
    FECHAULTIMACONSULTA, FLAG_AC, MONTOSALDODISPONIBLE_AC, MONTOSALDOMINIMO_AC, MONTOSALDOCONTABLE_AC, 
    MONTOINTERESACUANTCAP_AC, NROOPERACIONES_AC, FLAG_PF, MONTOSALDOCAPITAL_PF, NRODIASPLAZOFIJO_PF, 
    MONTOINTERESPACTADO_PF, MONTOINTERESPAGADO_PF, MONTOINTERESDEVENGADO_PF, TASAPAGADA_PF, NUMERORENOVACION_PF, 
    FLAG_CTS, MONTOCAPITAL_CTS, MONTOINTERES_CTS, MONTOCAPITALINTANGIBLE_CTS, MONTOINTERESINTANGIBLE_CTS, 
    FLAG_AP, MONTOCAPITAL_AP, MONTOCUOTA_AP, NROCUOTA_AP, TASAINCENTIVO_AP, FECHAVIGENCIA_AP, FECULTACTUALIZACION
)
SELECT 
    20251231, (SELECT PKCUENTAAHORRO FROM DCUENTAAHORRO WHERE CODCUENTAAHORRO='AHO0000801'), 
    pkproductoahorro, pkmoneda, pktipocuentaahorro, pktipotasaahorro, 
    (SELECT PKCLIENTE FROM DCLIENTE WHERE CODCLIENTE='CLI002010'), pkauxiliar, pkoperador, pkagencia, pkestadocuenta, tipocambio, 
    500.00, 0.00, 500.00, '2026-02-02', 
    500.00, tasainterescuenta, tasaefectivaanual, nrotitulares, nrofirmas, 
    flagexoneracionimpuesto, flagexoneracioncomision, flagcuentapromocion, nrooperacioneslibres, 
    '2026-02-02 00:00:00', 'S', 500.00, 50.00, 500.00, 
    0.00, 0, 'N', 0.00, 0, 
    0.00, 0.00, 0.00, 0.00, 0, 
    'N', 0.00, 0.00, 0.00, 0.00, 
    'N', 0.00, 0.00, 0, 0.00, NULL, NOW()
FROM FCUENTAAHORRO
WHERE PKCUENTAAHORRO = 1 AND PERIODODIA = 20251231;

COMMIT;
