-- ============================================================================
-- 09_DDL_simulador_gnb.sql
-- ----------------------------------------------------------------------------
-- Modificaciones a la base de datos para el simulador Banco GNB Perú.
-- Implementa:
--   1. Extensiones a DAGENCIA (Dirección, Anexos, Horario).
--   2. Tabla de Canales de Soporte Telefónico.
--   3. Roles de Homebanking (Personas/Empresas).
--   4. Alteraciones a USUARIOS_HOMEBANKING (Sello de seguridad, Token Digital).
--   5. Alteraciones a FOPERACIONES (Estado de Tx para CCE diferidas, Maker/Checker).
--   6. Tabla FCONFIGURACION_TARJETA.
-- ============================================================================

-- 1. Extensiones a DAGENCIA
ALTER TABLE DAGENCIA
ADD COLUMN IF NOT EXISTS DIRECCION VARCHAR(255),
ADD COLUMN IF NOT EXISTS ANEXOS_TELEFONICOS VARCHAR(100),
ADD COLUMN IF NOT EXISTS HORARIO_ATENCION VARCHAR(150);

-- 2. Canales de Soporte
CREATE TABLE IF NOT EXISTS DCANALES_SOPORTE (
    PKCANALSOPORTE SERIAL PRIMARY KEY,
    NOMBRE_CANAL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(50) NOT NULL,
    HORARIO_ATENCION VARCHAR(150),
    AMBITO_OPERACION TEXT,
    FECULTACTUALIZACION TIMESTAMP DEFAULT NOW()
);

-- 3. Roles de Homebanking
CREATE TABLE IF NOT EXISTS DROLES_HOMEBANKING (
    PKROL SERIAL PRIMARY KEY,
    CODROL VARCHAR(20) UNIQUE NOT NULL,
    DESROL VARCHAR(100) NOT NULL,
    TIPO_BANCA VARCHAR(20) NOT NULL -- PERSONAS o EMPRESAS
);

INSERT INTO DROLES_HOMEBANKING (CODROL, DESROL, TIPO_BANCA) VALUES
('TITULAR', 'Titular de Cuenta', 'PERSONAS'),
('ADICIONAL', 'Tarjeta Adicional', 'PERSONAS'),
('MAKER', 'Preparador / Operador', 'EMPRESAS'),
('CHECKER', 'Autorizador / Aprobador', 'EMPRESAS'),
('ADMIN_CANALES', 'Administrador de Canales', 'EMPRESAS')
ON CONFLICT (CODROL) DO NOTHING;

-- 4. Modificaciones a USUARIOS_HOMEBANKING
ALTER TABLE USUARIOS_HOMEBANKING
ADD COLUMN IF NOT EXISTS PKROL INT REFERENCES DROLES_HOMEBANKING(PKROL),
ADD COLUMN IF NOT EXISTS IMAGEN_SEGURIDAD VARCHAR(100),
ADD COLUMN IF NOT EXISTS TOKEN_ACTIVADO CHAR(1) DEFAULT 'N',
ADD COLUMN IF NOT EXISTS PIN_DIGITAL VARCHAR(255);

-- Asignar rol TITULAR por defecto a usuarios existentes que no tengan rol
UPDATE USUARIOS_HOMEBANKING
SET PKROL = (SELECT PKROL FROM DROLES_HOMEBANKING WHERE CODROL = 'TITULAR')
WHERE PKROL IS NULL;

-- 5. Modificaciones a FOPERACIONES para controlar transferencias diferidas y Maker/Checker
ALTER TABLE FOPERACIONES
ADD COLUMN IF NOT EXISTS ESTADO_TX VARCHAR(20) DEFAULT 'COMPLETADO', -- PENDIENTE, COMPLETADO, RECHAZADO
ADD COLUMN IF NOT EXISTS CANAL_ORIGEN VARCHAR(50) DEFAULT 'WEB',
ADD COLUMN IF NOT EXISTS TOKEN_DINAMICO VARCHAR(10);

-- 6. Configuraciones de Tarjeta de Crédito
CREATE TABLE IF NOT EXISTS FCONFIGURACION_TARJETA (
    PKCONFIG SERIAL PRIMARY KEY,
    PKCUENTACREDITO INT NOT NULL REFERENCES DCUENTACREDITO(PKCUENTACREDITO),
    COMPRAS_INTERNET CHAR(1) NOT NULL DEFAULT 'S',
    COMPRAS_EXTERIOR CHAR(1) NOT NULL DEFAULT 'N',
    DISPOSICION_EFECTIVO CHAR(1) NOT NULL DEFAULT 'S',
    SOBREGIRO CHAR(1) NOT NULL DEFAULT 'N',
    FECULTACTUALIZACION TIMESTAMP DEFAULT NOW(),
    UNIQUE (PKCUENTACREDITO)
);
